# Use the official Node.js image as the base image
FROM node:21-slim

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the dependencies
RUN npm install --no-audit --fund false

# Copy the rest of the files to the container
COPY . .

RUN ls -la

# Start the application
CMD ["node", "clewd.js"]
